name: Java CI (Gradle)
on: [ push, pull_request ]

jobs:
  build-java-17:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/gradle.yml@v1
    with:
      java-version: '17'
      upload-artifacts: false
      caching-refs: |
        refs/heads/gradle/multi-project
